function DATA = importDataTxtFile(filename, startRow, endRow,Type)
%IMPORTFILE Import numeric data from a text file as a matrix.
% Auto-generated by MATLAB on 2019/05/13 08:30:13
% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 1;
    endRow = inf;
    Type = 1;
end

% %%% ²âÊÔÓÃ
% clc
% clear
% 
% szFolder = 'E:\2019-12-01 S&C benchmark\¼ÆËã³ÌÐò\Run_5\Crossing\';
% as1Comp = {'CheckRail_Thr',...
%            'Crossing',...
%            'OppositeStockRail'}; 
% af1Side = [-1 ...
%            +1 ...
%            -1]; % used to mirror lefthand components       
% fTrackGauge = 1.435;
% fNomRailHalfWidth = 0.035;
% fRailCoordPosition = fTrackGauge/2 + fNomRailHalfWidth;
% iComp = 1;
% filename = [szFolder,'SectionPosition',as1Comp{iComp},'.txt'];
% % startRow = 1;
% startRow = [1,2,10];
% endRow = inf;
% Type = 1;
% delimiter = ' ';

% Format for each line of text:
if Type == 1 % master
    formatSpec = '%f %f%[^\n\r]';
else % profiles
    formatSpec = '%f %f%[^\n\r]';
end

% Open the text file.
fileID = fopen(filename,'r');

% Read columns of data according to the format.
% dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, ...
%     'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', ...
%     'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, ...
%     'EndOfLine', '\r\n');
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, ...
    'Delimiter', delimiter, 'MultipleDelimsAsOne', true, ...
    'HeaderLines', startRow(1)-1, 'ReturnOnError', false, ...
    'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, ...
        'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', ...
        'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, ...
        'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

% Close the text file.
fclose(fileID);

% Create output variable
DATA = [dataArray{1:end-1}];
end