function export_full_case_short_run_from_main(output_path, max_steps)
% Run a patched temporary copy of the MATLAB main script for a short Preload baseline.
%
% The original SDITT main script is not parameterized for short validation
% runs, so this helper patches only a temporary copy. The source script under
% SDITT-RW-FT-250728 is not modified.

if nargin < 1 || isempty(output_path)
    output_path = fullfile(tempdir, 'sditt_full_case_short_run_main_baseline.json');
end
if nargin < 2 || isempty(max_steps)
    max_steps = 1;
end

helper_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(fileparts(helper_dir));
matlab_dir = fullfile(repo_root, 'SDITT-RW-FT-250728');
source_path = fullfile(matlab_dir, 'SDITT_CR400_NoStrTIrr_250728_Face.m');
multi_con_path = fullfile(matlab_dir, 'Multi_Con_250812.m');
temporary_preload_mat_path = [tempname, '.mat'];
temporary_cal_mat_path = [tempname, '.mat'];
temporary_pre_state_path = [tempname, '.mat'];
temporary_script_path = [tempname(matlab_dir), '.m'];
[~, temporary_multi_name] = fileparts(tempname(matlab_dir));
temporary_multi_path = fullfile(matlab_dir, [temporary_multi_name, '.m']);

source = fileread(source_path);
patched = local_patch_main_script( ...
    source, temporary_preload_mat_path, temporary_cal_mat_path, temporary_pre_state_path, max_steps, temporary_multi_name);
patched_multi = local_patch_multi_con_function(fileread(multi_con_path), temporary_multi_name);

fid = fopen(temporary_script_path, 'w');
if fid < 0
    error('cannot create temporary script: %s', temporary_script_path);
end
fid_multi = fopen(temporary_multi_path, 'w');
if fid_multi < 0
    error('cannot create temporary function: %s', temporary_multi_path);
end
cleanup_file = onCleanup(@() local_cleanup( ...
    temporary_script_path, temporary_multi_path, temporary_preload_mat_path, ...
    temporary_cal_mat_path, temporary_pre_state_path));
fprintf(fid, '%s', patched);
fclose(fid);
fprintf(fid_multi, '%s', patched_multi);
fclose(fid_multi);

old_dir = pwd;
cleanup_dir = onCleanup(@() cd(old_dir));
addpath(helper_dir);
evalin('base', sprintf("cd('%s'); run('%s');", ...
    local_escape_path(matlab_dir), local_escape_path(temporary_script_path)));

export_full_case_short_run_baseline( ...
    {temporary_preload_mat_path, temporary_cal_mat_path}, output_path, {'Preload', 'Cal'}, max_steps);
end


function patched = local_patch_main_script( ...
    source, temporary_preload_mat_path, temporary_cal_mat_path, temporary_pre_state_path, max_steps, temporary_multi_name)
patched = strrep(source, sprintf('\r\n'), sprintf('\n'));
patched = strrep(patched, 'clearvars -except hwait kk_Cal', 'clearvars -except hwait kk_Cal');
patched = strrep(patched, 'Choose_Save = 1;', 'Choose_Save = 0;');
patched = strrep(patched, 'Multi_Con_250812(', [temporary_multi_name, '(']);
patched = strrep(patched, ...
    '    load Pre_CRH380A_009_Face_V350_zgygPf2_m2d5m.mat', ...
    sprintf('    load(''%s'')', strrep(temporary_pre_state_path, '''', '''''')));
patched = strrep(patched, ...
    '        InpPar.FWc = 47.5+0.1;            % �����ֶ��յ����', ...
    sprintf('        InpPar.FWc = j0 + InpPar.Vlc * drtaT * %.17g;            %% short-run endpoint', max_steps - 0.5));
patched = strrep(patched, ...
    '        InpPar.FWc = 110+(Par_Vehicle.Ll1+Par_Vehicle.Ll2)*2;            % �����ֶ��յ����', ...
    sprintf('        InpPar.FWc = j0 + InpPar.Vlc * drtaT * %.17g;            %% short-run Cal endpoint', max_steps - 0.5));
patched = strrep(patched, ...
    'xlzcs = ceil((InpPar.FWc-j0)*(-1)/InpPar.Vlc./drtaT)+xlcs_start;', ...
    sprintf('xlzcs = max(xlcs_start + %d + 4, 8); %% short-run storage length', max_steps));
patched = strrep(patched, local_gui_block(), 'hwait = [];');
patched = strrep(patched, local_waitbar_block(), '% short-run validation: waitbar disabled');
patched = strrep(patched, ...
    '            [Pxt, Q_temp] = WR_Force_VehicleSys_RotationIII(', ...
    sprintf(['            Con_Int.Pxt_before_WR(xcs,:) = Pxt(:,1)'';\n', ...
             '            [Pxt, Q_temp] = WR_Force_VehicleSys_RotationIII(']));

preload_save_block = local_stage_save_block(temporary_preload_mat_path);
cal_save_block = local_stage_save_block(temporary_cal_mat_path);
pre_state_block = local_pre_state_save_block(temporary_pre_state_path);
short_run_exit_block = sprintf([ ...
    '    if xlcs - xlcs_start >= %d\n', ...
    '        %% short-run validation: save accepted-step state and stop before the full route.\n', ...
    '        if strcmp(InpPar.Type_simulation, ''Preload'')\n', ...
    '%s', ...
    '%s', ...
    '            break\n', ...
    '        else\n', ...
    '%s', ...
    '            return\n', ...
    '        end\n', ...
    '    end\n'], ...
    max_steps, ...
    local_indent(preload_save_block, 12), ...
    local_indent(pre_state_block, 12), ...
    local_indent(cal_save_block, 12));
patched = strrep(patched, '    xlcs = xlcs + 1;', ...
    sprintf('    xlcs = xlcs + 1;\n%s', short_run_exit_block));
patched = strrep(patched, '% Save, Cxt, Park', [cal_save_block, '% Save, Cxt, Park']);
end


function patched = local_patch_multi_con_function(source, temporary_multi_name)
patched = strrep(source, sprintf('\r\n'), sprintf('\n'));
patched = strrep(patched, ...
    'function [Mileage, Con_str, Pjc, Pjch, Pjcc, Prhx, Prhxf] = Multi_Con_250812(', ...
    ['function [Mileage, Con_str, Pjc, Pjch, Pjcc, Prhx, Prhxf] = ', temporary_multi_name, '(']);
patched = strrep(patched, ...
    '[~, Normal_Force.(T), Area_STRIPES.(T), Con_STRIPES.(T), N_Stripes.(T), Epsilon.(T)] = NF_STRIPES_230623(', ...
    '[NorGap_ConCS.(T), Normal_Force.(T), Area_STRIPES.(T), Con_STRIPES.(T), N_Stripes.(T), Epsilon.(T)] = NF_STRIPES_230623(');
patched = strrep(patched, ...
    sprintf('    Con_str.Con_STRIPES = Con_STRIPES;\n    Con_str.Epsilon = Epsilon;'), ...
    sprintf(['    Con_str.Con_STRIPES = Con_STRIPES;\n', ...
             '    if ~exist(''NorGap_ConCS'', ''var''), NorGap_ConCS = struct; end\n', ...
             '    if ~exist(''Con_wheel_2_II'', ''var''), Con_wheel_2_II = struct; end\n', ...
             '    if ~exist(''Con_rail_1_II'', ''var''), Con_rail_1_II = struct; end\n', ...
             '    if ~exist(''Ver_Pen_a'', ''var''), Ver_Pen_a = struct; end\n', ...
             '    Con_str.NorGap_ConCS = NorGap_ConCS;\n', ...
             '    Con_str.Con_wheel_2_II = Con_wheel_2_II;\n', ...
             '    Con_str.Con_rail_1_II = Con_rail_1_II;\n', ...
             '    Con_str.Ver_Pen_a = Ver_Pen_a;\n', ...
             '    Con_str.Epsilon = Epsilon;']));
end


function text = local_gui_block()
text = sprintf([ ...
    'if ~exist(''hwait'', ''var'')\n', ...
    '    hwait = waitbar(0,''Progress = 0%%'');\n', ...
    'end\n', ...
    'h = figure(2);\n', ...
    'pic = get(h, ''Position'');\n', ...
    'set(hwait, ''Units'', ''centimeters'', ''Position'', [pic(1), pic(2)-2.8, 9.65, 2]);\n']);
end


function text = local_waitbar_block()
text = sprintf([ ...
    '        waitbar(rate/100,hwait,[''Mileage = '', num2str(fix((j1-(Par_Vehicle.Ll1+Par_Vehicle.Ll2)*2*sign(strcmp(InpPar.VehicleDir, ''Trail'')))*1000)/1000), ...\n', ...
    '                      ''m; Steps = '', num2str(xlcs), ''; Progress = '' num2str(fix(rate*100)/100) ''%%'']);']);
end


function text = local_stage_save_block(mat_path)
text = sprintf([ ...
    'xlcs_short_run = xlcs - 1;\n', ...
    'save(''%s'', ''InpPar'', ''DOF_sum'', ''N_Patch_sum'', ''T'', ''drtaT'', ''j1'', ''xlcs_short_run'', ', ...
    '''xcs_PreviousStep'', ''ZP_IntError_Nor'', ''ZP_IntError_NorTan'', ', ...
    '''Pxt_Gravity'', ', ...
    '''Pjc'', ''Pjch'', ''Pjcc'', ''Prhx'', ''Prhxf'', ''Dis_Rail'', ''Vel_Rail'', ''Acc_Rail'', ', ...
    '''ZP_Dis'', ''ZP_Vel'', ''ZP_Acc'', ''ZP_Load'', ''ZP_NF'', ''d0'', ''Con_WS'', ''Con_Int'', ', ...
    '''ShapeFunction'', ''RailBeam_Motion'', ''DynStatus_Rail'', ''-v7'');\n'], ...
    strrep(mat_path, '''', ''''''));
end


function text = local_pre_state_save_block(mat_path)
text = sprintf([ ...
    'clear Pre\n', ...
    'Pre.drtaT = drtaT; Pre.d0 = d0; Pre.j1 = j1;\n', ...
    'Pre.Pjcc = Pjcc; Pre.Pjch = Pjch; Pre.Prhxf = Prhxf;\n', ...
    'Pre.Zwy = repmat(Zwy(:,4), 1, 3); Pre.Zsd = repmat(Zsd(:,4), 1, 3); Pre.Zjsd = repmat(Zjsd(:,4), 1, 3);\n', ...
    'Pre.NF = repmat(Pjc(:,2), 1, 3); Pre.Con_WS = Con_WS;\n', ...
    'if exist(''pos_Radius_Vehicle'', ''var''), Pre.pos_Radius_Vehicle = pos_Radius_Vehicle; end\n', ...
    'if exist(''pos_Body_global'', ''var''), Pre.pos_Body_global = pos_Body_global; end\n', ...
    'if exist(''pos_WS_BogieCS'', ''var''), Pre.pos_WS_BogieCS = pos_WS_BogieCS; end\n', ...
    'if exist(''pos_BG_CarbodyCS'', ''var''), Pre.pos_BG_CarbodyCS = pos_BG_CarbodyCS; end\n', ...
    'if exist(''pos_yaw_track'', ''var''), Pre.pos_yaw_track = pos_yaw_track; end\n', ...
    'Pre.drtaT_His = drtaT_His;\n', ...
    'Pre.ZP_Con = struct; Pre.ZP_Con.RelVel_max = struct;\n', ...
    'for i2_short = 1:1:InpPar.N_ConPatch\n', ...
    '    T2_short = InpPar.Exp_DummyRail{i2_short};\n', ...
    '    Source_short = ZP_Con.RelVel_max.(T2_short);\n', ...
    '    Pre.ZP_Con.RelVel_max.(T2_short) = cell(size(Source_short));\n', ...
    '    for m_short = 1:1:size(Source_short,1)\n', ...
    '        for n_short = 1:1:size(Source_short,2)\n', ...
    '            if ~isempty(Source_short{m_short,n_short})\n', ...
    '                row_short = min(size(Source_short{m_short,n_short},1), xlcs);\n', ...
    '                Pre.ZP_Con.RelVel_max.(T2_short){m_short,n_short} = Source_short{m_short,n_short}(row_short,:);\n', ...
    '            end\n', ...
    '        end\n', ...
    '    end\n', ...
    'end\n', ...
    'Pre.ZP_T = ZP_Dyn.T(max(1,end-2):end,:);\n', ...
    'Pre.ZP_Dis = repmat(Zwy(:,4).'', 3, 1); Pre.ZP_Vel = repmat(Zsd(:,4).'', 3, 1); Pre.ZP_Acc = repmat(Zjsd(:,4).'', 3, 1);\n', ...
    'Pre.ZP_Load = repmat(Pxt(:,1).'', 3, 1);\n', ...
    'save(''%s'', ''Pre'', ''-v7'');\n'], ...
    strrep(mat_path, '''', ''''''));
end


function local_cleanup(varargin)
for index = 1:numel(varargin)
    path_value = varargin{index};
    if exist(path_value, 'file')
        delete(path_value);
    end
end
end


function escaped = local_escape_path(path_value)
escaped = strrep(path_value, '''', '''''');
end


function indented = local_indent(text, spaces)
prefix = repmat(' ', 1, spaces);
lines = splitlines(string(text));
for index = 1:numel(lines)
    if strlength(lines(index)) > 0
        lines(index) = prefix + lines(index);
    end
end
indented = char(join(lines, newline));
end
