"""Simulation orchestration and full-system matrix assembly."""

from .no_contact import (
    HarmonicForce,
    NoContactSimulationResult,
    run_default_no_contact_smoke,
    run_no_contact_forced_response,
)
from .coupled import (
    CoupledIterationSettings,
    CoupledStepCallbacks,
    CoupledStepState,
    CoupledTimeIterationResult,
    run_coupled_time_iteration,
)
from .full_case import (
    FullCaseContactDiagnostics,
    FullCaseFrozenContactInput,
    FullCaseIterationRecord,
    FullCaseOutputRow,
    FullCaseProfileSnapshot,
    FullCaseProgressEvent,
    FullCaseRailRecovery,
    FullCaseSideProfileSnapshot,
    FullDefaultCasePreparation,
    FullDefaultCaseRunResult,
    FullDefaultCaseSettings,
    FullDefaultCaseStageResult,
    MissingFullCasePhysicsError,
    MissingFullCaseStage,
    find_default_full_case_checkpoint,
    prepare_default_full_case,
    run_default_full_case_driver,
)
from .small_case import (
    SmallRigidWheelsetCase,
    SmallRigidWheelsetResult,
    export_small_rigid_wheelset_curve,
    run_small_rigid_wheelset_case,
)
from .system import (
    SystemDofLayout,
    SystemMatrices,
    SparseSystemMatrices,
    assemble_sparse_system_matrices,
    assemble_system_matrices,
    build_default_modal_rw_system_matrices,
    build_default_sparse_modal_rw_system_matrices,
)

__all__ = [
    "HarmonicForce",
    "CoupledIterationSettings",
    "CoupledStepCallbacks",
    "CoupledStepState",
    "CoupledTimeIterationResult",
    "FullCaseContactDiagnostics",
    "FullCaseFrozenContactInput",
    "FullCaseIterationRecord",
    "FullCaseOutputRow",
    "FullCaseProfileSnapshot",
    "FullCaseProgressEvent",
    "FullCaseRailRecovery",
    "FullCaseSideProfileSnapshot",
    "FullDefaultCasePreparation",
    "FullDefaultCaseRunResult",
    "FullDefaultCaseSettings",
    "FullDefaultCaseStageResult",
    "MissingFullCasePhysicsError",
    "MissingFullCaseStage",
    "NoContactSimulationResult",
    "SmallRigidWheelsetCase",
    "SmallRigidWheelsetResult",
    "SystemDofLayout",
    "SystemMatrices",
    "SparseSystemMatrices",
    "assemble_sparse_system_matrices",
    "assemble_system_matrices",
    "build_default_modal_rw_system_matrices",
    "build_default_sparse_modal_rw_system_matrices",
    "find_default_full_case_checkpoint",
    "prepare_default_full_case",
    "run_coupled_time_iteration",
    "run_default_full_case_driver",
    "run_default_no_contact_smoke",
    "run_no_contact_forced_response",
    "run_small_rigid_wheelset_case",
    "export_small_rigid_wheelset_curve",
]
